document.write("<div class=\"floating-menu\">");
document.write("    <h3>Index<\/h3>");
document.write("");
document.write("    <ul>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_intro.html\">What is Arrow<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_quick.html\">Arrow Quick Installation<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_getting_started.html\">Getting Started With Arrow<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_tutorial.html\">Arrow Tutorial<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            Arrow in Depth");
document.write("            <ul>");
document.write("                <li>");
document.write("                    <a href=\"arrow_test-suite-organization.html\">Test Suite Organization<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_configuration.html\">Configuration<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_controller.html\">Complex Test Scenarios<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_running-tests.html\">Re-Using Browser Sessions<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_parallelism.html\">Parallelism<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_reporting.html\">Reporting<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_proxy.html\">Using Proxy<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_YUI-asserts.html\">More YUI Asserts<\/a>");
document.write("                <\/li>");
document.write("");
document.write("                <li>");
document.write("                    <a href=\"arrow_replaceParamJSON.html\">Replacing parameters in descriptor<\/a>");
document.write("                <\/li>");
document.write("");
document.write("            <\/ul>");
document.write("");
document.write("");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_code-coverage.html\">Code Coverage<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_CI.html\">Arrow and Continuous Integration<\/a>");
document.write("        <\/li>");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_extending.html\">Extending And Developing Arrow<\/a>");
document.write("        <\/li>");
document.write("");
document.write("");
document.write("        <li>");
document.write("            <a href=\"arrow_FAQs.html\">Arrow FAQs<\/a>");
document.write("        <\/li>");
document.write("");
document.write("");
document.write("    <\/ul>");
document.write("");
document.write("<\/div>");
document.write("");